networks:
  traefik_default:
    external: true
version: "3"
services:
  server:
    image: gitea/gitea:1.16.8
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - traefik_default
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.gitea.rule=Host(`git.mrbuttlicker.xyz`)"
    - "traefik.http.services.gitea-websecure.loadbalancer.server.port=3000"
    - "traefik.http.routers.gitea.tls=true"
