services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/lord/docker/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 8080:8080
      - 7878:7878
      - 8989:8989
      - 9696:9696
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped


  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: service:wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - /home/lord/docker/qbittorrent/downloads:/downloads
      - /home/lord/docker/qbittorrent/config:/config
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:wireguard
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
    volumes:
      - /home/lord/docker/radarr/config:/config
      - /home/lord/media/movies:/movies
      - /home/lord/docker/qbittorrent/downloads:/downloads
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: service:wireguard
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
    volumes:
      - /home/lord/docker/sonnar/config:/config
      - /home/lord/media:/tv #optional
      - /home/lord/docker/qbittorrent/downloads:/downloads #optional
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    network_mode: service:wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/lord/docker/prowlarr/config:/config
    restart: unless-stopped








