version: "2.1"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/lord/docker/sabnzbd/config:/config
      - /home/lord/docker/sabnzbd/downloads:/downloads
  #    - /home/lord/docker/sabnzbd/downloads/incomplete:/incomplete-downloads
    ports:
      - 8080:8080
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    ports:
      - 7878:7878
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
    volumes:
      - /home/lord/docker/radarr/config:/config
      - /home/lord/media/movies:/movies
      - /home/lord/docker/sabnzbd/downloads/:/downloads
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
    volumes:
      - /home/lord/docker/sonnar/config:/config
      - /home/lord/media:/tv #optional
      - /home/lord/docker/sabnzbd/downloads/complete:/downloads #optional
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/lord/docker/prowlarr/config:/config
    restart: unless-stopped







