version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/root/docker/transmisson/data:/data'
            - '/root/docker/transmisson/ovpn/:/etc/openvpn/custom/'

        environment:
            - OPENVPN_PROVIDER=custom
            - OPENVPN_CONFIG=mexico
            - OPENVPN_USERNAME=
            - OPENVPN_PASSWORD=5
            - LOCAL_NETWORK=10.0.0.0/24
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn




